# Generated by Django 5.2.15 on 2026-07-07 06:52

import django.core.validators
import routers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('modello_hardware', models.CharField(blank=True, max_length=100)),
                ('versione_routeros', models.CharField(blank=True, max_length=50)),
                ('ip_pubblico_o_ddns', models.CharField(max_length=255)),
                ('porta_ssh', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('porta_api', models.PositiveIntegerField(default=8728, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', routers.fields.EncryptedCharField()),
                ('password', routers.fields.EncryptedCharField()),
                ('ip_vpn', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('chiave_pubblica_wireguard', models.CharField(blank=True, max_length=100)),
                ('stato_connessione', models.CharField(choices=[('non_configurato', 'Non configurato'), ('in_attesa_vpn', 'In attesa VPN'), ('connesso', 'Connesso'), ('offline', 'Offline')], default='non_configurato', max_length=20)),
                ('intervallo_backup', models.DurationField(blank=True, help_text='Intervallo tra un backup automatico e il successivo (usato dalla Fase 4).', null=True)),
                ('accesso_pubblico_bloccato', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
