# Generated by Django 5.2.15 on 2026-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='backup_retention_count',
            field=models.PositiveIntegerField(default=10, help_text='Numero di backup più recenti da conservare per questo router; i più vecchi vengono eliminati.'),
        ),
    ]
