# Generated by Django 5.2.15 on 2026-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_router_backup_retention_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='fallimenti_polling_consecutivi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contatore di polling falliti di fila (Fase 5); azzerato al primo successo.'),
        ),
    ]
