# Generated by Django 5.2.15 on 2026-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_router_fallimenti_polling_consecutivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='ip_lan',
            field=models.GenericIPAddressField(blank=True, help_text='IP del router nella rete locale, utile per test diretti prima di configurare la VPN.', null=True, protocol='IPv4'),
        ),
    ]
