# Generated by Django 5.2.15 on 2026-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_router_ip_lan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip_pubblico_o_ddns',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
