# Generated by Django 5.2.15 on 2026-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0005_alter_router_ip_pubblico_o_ddns'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='cliente_id',
            field=models.UUIDField(blank=True, help_text="Riferimento all'anagrafica clienti condivisa del Portale, per raggruppare i router.", null=True, verbose_name='ID cliente'),
        ),
    ]
