# Generated by Django 5.2.16 on 2026-08-18 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0006_router_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Il nome non può contenere andare a capo.', regex='^[^\\r\\n]*$')]),
        ),
    ]
