# Generated by Django 5.2.15 on 2026-07-08 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalVpnDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chiave_pubblica', models.CharField(max_length=44, unique=True)),
                ('ip_vpn', models.GenericIPAddressField(protocol='IPv4')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('revocato_il', models.DateTimeField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi_vpn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
    ]
