# Generated by Django 5.2.15 on 2026-07-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0002_router_backup_retention_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('binario', 'Backup binario (.backup)'), ('export', 'Export testuale (.rsc)')], max_length=20)),
                ('esito', models.CharField(choices=[('riuscito', 'Riuscito'), ('fallito', 'Fallito')], max_length=20)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('dimensione_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('errore', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='routers.router')),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
    ]
