# Generated by Django 5.2.15 on 2026-07-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_cleanup_periodic_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='s3_key',
            new_name='storage_path',
        ),
    ]
