# Generated by Django 5.2.15 on 2026-08-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_rename_s3_key_backup_storage_path'),
        ('routers', '0005_alter_router_ip_pubblico_o_ddns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_corso', 'In corso'), ('completato', 'Completato')], default='in_corso', max_length=12)),
                ('log', models.TextField(blank=True, default='')),
                ('avviato_il', models.DateTimeField(auto_now_add=True)),
                ('concluso_il', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_run', to='routers.router')),
            ],
            options={
                'ordering': ['-avviato_il'],
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backups.backuprun'),
        ),
    ]
