"""
Django settings for mkremote project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-hu!y46nk5-#d@w8=9^h18n%g*&q#)n_g9hh35ek=y0_dsrszv-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]

# Chiave master Fernet per la cifratura simmetrica delle credenziali router (Fase 1).
# Mai in chiaro nel codice: deve arrivare da env. Generarla con:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
MASTER_ENCRYPTION_KEY = os.environ.get('MASTER_ENCRYPTION_KEY')

# Pianificazione subnet VPN WireGuard hub-and-spoke (vedi Fase 0 / Fase 2).
# Configurabile da env, mai hardcoded altrove nel codice.
VPN_SUBNET_CIDR = os.environ.get('VPN_SUBNET_CIDR', '10.10.0.0/24')
VPN_HUB_IP = os.environ.get('VPN_HUB_IP', '10.10.0.1')
VPN_PERSONAL_IP_RANGE_START = os.environ.get('VPN_PERSONAL_IP_RANGE_START', '10.10.0.2')
VPN_PERSONAL_IP_RANGE_END = os.environ.get('VPN_PERSONAL_IP_RANGE_END', '10.10.0.9')
VPN_ROUTER_IP_RANGE_START = os.environ.get('VPN_ROUTER_IP_RANGE_START', '10.10.0.10')

# Hub WireGuard sul VPS (Fase 2). Il VPS non è ancora provisionato (vedi fase_8):
# questi valori restano vuoti finché non esiste un hub reale da raggiungere.
VPN_HUB_PUBLIC_ENDPOINT = os.environ.get('VPN_HUB_PUBLIC_ENDPOINT', '')  # es. vps.example.com
VPN_HUB_PUBLIC_PORT = os.environ.get('VPN_HUB_PUBLIC_PORT', '51820')
VPN_HUB_PUBLIC_KEY = os.environ.get('VPN_HUB_PUBLIC_KEY', '')  # chiave pubblica WireGuard del VPS

# Accesso SSH al VPS per gestire i peer WireGuard (wg set / wg syncconf).
VPS_SSH_HOST = os.environ.get('VPS_SSH_HOST', '')
VPS_SSH_PORT = int(os.environ.get('VPS_SSH_PORT', '22'))
VPS_SSH_USER = os.environ.get('VPS_SSH_USER', 'root')
VPS_SSH_PRIVATE_KEY_PATH = os.environ.get('VPS_SSH_PRIVATE_KEY_PATH', '')
VPN_WG_INTERFACE = os.environ.get('VPN_WG_INTERFACE', 'wg0')
VPN_WG_CONF_PATH = os.environ.get('VPN_WG_CONF_PATH', '/etc/wireguard/wg0.conf')

# Spazio FTPS Aruba (FTP con cifratura TLS esplicita) per i backup router
# (Fase 4). Preferito a un vero Object Storage: già disponibile, cifrato in
# transito. Vedi fase_8 per la motivazione della scelta.
BACKUP_FTP_HOST = os.environ.get('BACKUP_FTP_HOST', '')
BACKUP_FTP_PORT = int(os.environ.get('BACKUP_FTP_PORT', '21'))
BACKUP_FTP_USER = os.environ.get('BACKUP_FTP_USER', '')
BACKUP_FTP_PASSWORD = os.environ.get('BACKUP_FTP_PASSWORD', '')
BACKUP_FTP_BASE_PATH = os.environ.get('BACKUP_FTP_BASE_PATH', 'mikrotik-backups')

# Polling di monitoraggio e alert (Fase 5).
MONITORING_POLL_INTERVAL_SECONDS = int(os.environ.get('MONITORING_POLL_INTERVAL_SECONDS', '120'))

# Bot Telegram per gli alert (token da @BotFather); il chat_id destinatario è
# invece configurabile da interfaccia (AlertSettings), non da env, perché può
# cambiare senza bisogno di un redeploy.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# SMTP per gli alert via email (Fase 5). Se non configurato, EMAIL_BACKEND
# resta quello di sviluppo di Django (stampa le email in console).
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'mkremote@example.com')


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'routers',
    'vpn',
    'backups',
    'monitoring',
    'accounts',
    'terminal',
]

ASGI_APPLICATION = 'mkremote.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mkremote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mkremote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'mkremote'),
        'USER': os.environ.get('DB_USER', 'mkremote'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Channels (Fase 6: terminale SSH nel browser). DB Redis separato da Celery
# (indice 1 invece di 0) per non mescolare i messaggi dei due sistemi.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.environ.get('CHANNELS_REDIS_URL', 'redis://localhost:6379/1')],
        },
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'router-list'
LOGOUT_REDIRECT_URL = 'login'

if not DEBUG:
    # Il VPS è dietro Nginx che termina TLS e inoltra a Daphne su localhost:
    # senza questo header Django non saprebbe che la richiesta originale era HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
