# Generated by Django 5.2.15 on 2026-07-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0003_router_fallimenti_polling_consecutivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soglia_cpu_percent', models.PositiveSmallIntegerField(default=90)),
                ('soglia_temperatura_celsius', models.SmallIntegerField(default=70)),
                ('fallimenti_consecutivi_per_offline', models.PositiveSmallIntegerField(default=3)),
                ('cooldown_minuti', models.PositiveIntegerField(default=60, help_text='Tempo minimo tra due notifiche ripetute dello stesso alert ancora aperto.')),
                ('telegram_abilitato', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('email_abilitata', models.BooleanField(default=False)),
                ('email_destinatario', models.EmailField(blank=True, max_length=254)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni alert',
                'verbose_name_plural': 'Impostazioni alert',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('offline', 'Router offline'), ('cpu_alta', 'CPU sopra soglia'), ('temperatura_alta', 'Temperatura sopra soglia'), ('backup_fallito', 'Backup fallito')], max_length=30)),
                ('stato', models.CharField(choices=[('aperto', 'Aperto'), ('chiuso', 'Chiuso')], default='aperto', max_length=10)),
                ('messaggio', models.CharField(blank=True, max_length=500)),
                ('aperto_il', models.DateTimeField(auto_now_add=True)),
                ('chiuso_il', models.DateTimeField(blank=True, null=True)),
                ('ultima_notifica_il', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='routers.router')),
            ],
            options={
                'ordering': ['-aperto_il'],
                'indexes': [models.Index(fields=['router', 'tipo', 'stato'], name='monitoring__router__ab1514_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouterMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ram_usata_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ram_totale_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uptime_secondi', models.PositiveBigIntegerField(blank=True, null=True)),
                ('temperatura_celsius', models.SmallIntegerField(blank=True, null=True)),
                ('traffico_interfacce', models.JSONField(blank=True, default=dict)),
                ('rilevato_il', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metriche', to='routers.router')),
            ],
            options={
                'ordering': ['-rilevato_il'],
                'indexes': [models.Index(fields=['router', '-rilevato_il'], name='monitoring__router__374659_idx')],
            },
        ),
    ]
