# Generated by Django 5.2.15 on 2026-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_poll_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='routermetric',
            name='disco_totale_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routermetric',
            name='disco_usato_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
